# Goal

int32 SINGLE_PATH_RUN=0
int32 ALL_PATHS_UNTIL_SELECTED_RUN=1

int32 action

# TODO: simulation speed

# Joint trajectory
trajectory_msgs/JointTrajectory[] joint_traj_array

# wait for execution to finish before returning
bool wait_for_execution

# Use the simulated robot or the actual robot
bool simulate

# Process parameters
# godel_msgs/BlendingPlanParameters blend_params
# godel_msgs/ScanPlanParameters scan_params

---
# Result

bool success

---
# Feedback is empty (primary concern is that task completes)
