# Goal
int32 GENERATE_MOTION_PLAN_AND_PREVIEW=1
int32 PREVIEW_TOOL_PATH=2

int32 action

# index of selected path
int32 index

# bool use_default_parameters

---

# Result
bool succeeded

---

# Feedback
string last_completed
