
# action specification, see enumeration above
# int32 action

framefab_msgs/ModelInputParameters model_params
framefab_msgs/TaskSequenceInputParameters task_sequence_params

---

#Result
bool succeeded

---

# Feedback
string last_completed
