set(_CATKIN_CURRENT_PACKAGE "kuka_kr10_support")
set(kuka_kr10_support_VERSION "0.1.0")
set(kuka_kr10_support_MAINTAINER "G.A. vd. Hoorn (TU Delft Robotics Institute) <g.a.vanderhoorn@tudelft.nl>")
set(kuka_kr10_support_PACKAGE_FORMAT "2")
set(kuka_kr10_support_BUILD_DEPENDS "pluginlib" "eigen" "moveit_core" "moveit_ros_planning_interface" "moveit_ros_perception" "interactive_markers" "geometric_shapes" "moveit_visual_tools")
set(kuka_kr10_support_BUILD_EXPORT_DEPENDS )
set(kuka_kr10_support_BUILDTOOL_DEPENDS "catkin")
set(kuka_kr10_support_BUILDTOOL_EXPORT_DEPENDS )
set(kuka_kr10_support_EXEC_DEPENDS "industrial_robot_client" "joint_state_publisher" "kuka_resources" "robot_state_publisher" "rviz" "xacro" "pluginlib" "moveit_core" "moveit_fake_controller_manager" "moveit_ros_planning_interface" "moveit_ros_perception" "interactive_markers" "moveit_visual_tools")
set(kuka_kr10_support_RUN_DEPENDS "industrial_robot_client" "joint_state_publisher" "kuka_resources" "robot_state_publisher" "rviz" "xacro" "pluginlib" "moveit_core" "moveit_fake_controller_manager" "moveit_ros_planning_interface" "moveit_ros_perception" "interactive_markers" "moveit_visual_tools")
set(kuka_kr10_support_TEST_DEPENDS "roslaunch")
set(kuka_kr10_support_DOC_DEPENDS )
set(kuka_kr10_support_DEPRECATED "")