// register IKFastKinematicsPlugin as a KinematicsBase implementation
#include <kr6_r900_workspace_ikfast_manipulator_plugin/kr6_r900_workspace_manipulator_ikfast_moveit_plugin.hpp>
#include <pluginlib/class_list_macros.h>
PLUGINLIB_EXPORT_CLASS(kr6_r900_workspace_ikfast_manipulator_plugin::IKFastKinematicsPlugin, kinematics::KinematicsBase);
