int32 FIND_ONLY=0
int32 COMPUTE_AND_FIND=1 #not supported now

# action specification, see enumeration above
int32 action

bool use_default_parameters
framefab_msgs/ModelInputParameters model_params
framefab_msgs/PathInputParameters path_params
string name

---

bool model_found
bool paths_found

# visualization & PathCandidate
# visualization_msgs/MarkerArray surfaces
# geometry_msgs/PoseArray robot_scan_poses

framefab_msgs/ModelInputParameters model_params # parameter values used in latests results
framefab_msgs/PathInputParameters path_params # parameter values used in latests results
