int32 ALL=-1

# selected path id
int32 index

# process planning parameters
framefab_msgs/ProcessPlanningParameters params

# working env collision objs
moveit_msgs/CollisionObject[] env_collision_objs

# the actual path the tool will follow
framefab_msgs/ElementCandidatePoses[] process_path

---

framefab_msgs/UnitProcessPlan[] plan
