int32 ALL=-1

# selected task id
int32 index

# working env collision objs
moveit_msgs/CollisionObject[] env_collision_objs

# sequenced collision objs
framefab_msgs/WireFrameCollisionObject[] wf_collision_objs

# the actual path the tool will follow
framefab_msgs/ElementCandidatePoses[] task_sequence

bool use_saved_graph

string file_name

float64 clt_rrt_unit_process_timeout

float64 clt_rrt_timeout

---

framefab_msgs/UnitProcessPlan[] plan
