int32 READ_WIREFRAME=0
int32 TASK_SEQUENCE_SEARCHING=1

int32 action

framefab_msgs/ModelInputParameters model_params
framefab_msgs/TaskSequenceInputParameters task_sequence_params

---

# save result
bool succeeded

# joint pose for reset position
framefab_msgs/ElementCandidatePoses[] element_array