int32 READ_WIREFRAME=0
int32 TASK_SEQUENCE_SEARCHING=1
int32 REQUEST_COLLISION_OBJS=2

int32 action

framefab_msgs/ModelInputParameters model_params
framefab_msgs/TaskSequenceInputParameters task_sequence_params

framefab_msgs/ElementCandidatePoses[] element_array

---

# save result
bool succeeded

framefab_msgs/ElementCandidatePoses[] element_array

# partially shrinked collision objs
framefab_msgs/WireFrameCollisionObject[] wf_collision_objs
